global using DynamicReporting.Api.Application.DTOs;
global using DynamicReporting.Api.Application.Services;
global using DynamicReporting.Api.Application.Validators;
global using DynamicReporting.Api.Domain.Interfaces;
global using DynamicReporting.Api.Domain.Models;
global using DynamicReporting.Api.Domain.Models.Entities;
global using DynamicReporting.Api.Infrastructure.Persistence;
global using DynamicReporting.Api.Infrastructure.Persistence.Context;
global using DynamicReporting.Api.Infrastructure.Persistence.Context;
global using DynamicReporting.Api.Infrastructure.Persistence.Query;
global using DynamicReporting.Api.Infrastructure.Persistence.Repository;
global using FluentAssertions;
global using FluentValidation.TestHelper;
global using Microsoft.EntityFrameworkCore;
global using Moq;
global using Swashbuckle.AspNetCore.Annotations;
global using System.Collections.Generic;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Threading.Tasks;
global using Tests.Infrastructure.Tests;
global using Xunit;
global using DynamicReporting.Api.Shared.Helper;
global using Microsoft.EntityFrameworkCore.Metadata;
global using DynamicReporting.Api.Infrastructure.Persistence.Helper;
global using Microsoft.Data.Sqlite;

namespace Tests;

public class GlobalUsing;